AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  tech-challenge-lambda

  Função Lambda para autenticacao de um usuário via CPF - FIAP Tech Challenge

Globals:
  Function:
    Timeout: 3

Parameters:
  UserPoolId:
    Type: String
  ClientId:
    Type: String
  Host:
    Type: String
  Port:
    Type: Number
  User:
    Type: String
  DatabasePassword:
    Type: String
  DatabaseName:
    Type: String

Resources:
  AuthenticationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: authenticate/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Events:
        Authentication:
          Type: Api
          Properties:
            Path: /authenticate
            Method: post
      Environment:
        Variables:
          UserPoolId: !Ref UserPoolId
          ClientId: !Ref ClientId
          Host: !Ref Host
          Port: !Ref Port
          User: !Ref User
          DatabasePassword: !Ref DatabasePassword
          DatabaseName: !Ref DatabaseName